import type { Listing } from "./types";

export const ALL_LISTINGS: Omit<Listing, "fitScore">[] = [
  {
    id: "1",
    name: "Cascade Pest Solutions",
    type: "Pest Control",
    askingPrice: 425000,
    revenue: 680000,
    sde: 148000,
    location: "Bellevue, WA",
    state: "WA",
    description:
      "Established residential and commercial pest control serving King County since 2011. Strong recurring revenue base with 340+ active service contracts. Fully licensed, 3 technicians included. Owner works ~25 hrs/week on admin and sales.",
    yearEstablished: 2011,
    employees: 4,
    ownerHoursPerWeek: 25,
    leaseTerm: "Office lease: 2 yrs remaining, 3-yr renewal at $1,800/mo",
    growthTrend: "growing",
    sdeMargin: 22,
    multipleOnAsk: 2.87,
    highlights: [
      "340+ active recurring contracts — ~68% residential, 32% commercial",
      "22% SDE margin with room to grow via commercial upsells",
      "All technician licenses transferable to new owner",
      "Google rating 4.8 ★ (212 reviews) — strong local brand",
    ],
  },
  {
    id: "2",
    name: "Harbor Clean Coin Laundry",
    type: "Laundromat",
    askingPrice: 280000,
    revenue: 145000,
    sde: 72000,
    location: "Tacoma, WA",
    state: "WA",
    description:
      "Well-maintained 28-machine coin laundromat with a loyal neighborhood customer base. Low owner involvement — currently runs ~8 hrs/week. All machines serviced within last 18 months. Long-term lease with 5-yr renewal option.",
    yearEstablished: 2009,
    employees: 1,
    ownerHoursPerWeek: 8,
    leaseTerm: "4 yrs remaining, 5-yr renewal option at $3,200/mo",
    growthTrend: "stable",
    sdeMargin: 50,
    multipleOnAsk: 3.89,
    highlights: [
      "Near-absentee operation — owner on-site ~8 hrs/week only",
      "50% SDE margin — one of the highest in the service sector",
      "28 machines: 18 washers + 10 dryers, all recently serviced",
      "Stable neighborhood anchor with no direct competition within 1.2 miles",
    ],
  },
  {
    id: "3",
    name: "Green Thumb Landscaping Co.",
    type: "Landscaping",
    askingPrice: 520000,
    revenue: 890000,
    sde: 185000,
    location: "Kirkland, WA",
    state: "WA",
    description:
      "Full-service residential and HOA landscaping company operating since 2007 with 60+ recurring maintenance contracts. Fleet of 4 trucks and trailer included. Strong pipeline of seasonal installs. Owner works 35 hrs/week.",
    yearEstablished: 2007,
    employees: 8,
    ownerHoursPerWeek: 35,
    leaseTerm: "Yard/storage lease: 1 yr remaining, month-to-month option",
    growthTrend: "growing",
    sdeMargin: 21,
    multipleOnAsk: 2.81,
    highlights: [
      "60+ HOA and residential maintenance contracts — highly recurring revenue",
      "Fleet included: 4 trucks, 2 trailers, full equipment inventory",
      "Two experienced crew leads capable of managing operations independently",
      "Pipeline of $120K+ in scheduled spring install projects",
    ],
  },
  {
    id: "4",
    name: "Sparkling Spaces Cleaning",
    type: "Cleaning Service",
    askingPrice: 195000,
    revenue: 410000,
    sde: 98000,
    location: "Redmond, WA",
    state: "WA",
    description:
      "Residential and light commercial cleaning service with a trained team of 6 cleaners and 85 active weekly/bi-weekly clients. Owner handles scheduling and quality checks (~20 hrs/week). Consistent 5-star ratings on Yelp and Google.",
    yearEstablished: 2015,
    employees: 6,
    ownerHoursPerWeek: 20,
    leaseTerm: "Home-based operations — no commercial lease",
    growthTrend: "growing",
    sdeMargin: 24,
    multipleOnAsk: 1.99,
    highlights: [
      "85 active recurring clients — 70% weekly, 30% bi-weekly schedules",
      "Low asking price: 1.99x SDE — strong value relative to cash flow",
      "Experienced 6-person team — all W-2 employees with background checks",
      "4.9 ★ on Google (178 reviews) and top-ranked on Yelp in Redmond",
    ],
  },
  {
    id: "5",
    name: "Olympic Bay Gifts & Apparel",
    type: "Retail",
    askingPrice: 310000,
    revenue: 540000,
    sde: 112000,
    location: "Olympia, WA",
    state: "WA",
    description:
      "Destination gift and apparel boutique in downtown Olympia's tourist district. High foot traffic, strong seasonal peaks. 2,400 sq ft space with established vendor relationships. Owner retiring after 14 years.",
    yearEstablished: 2010,
    employees: 3,
    ownerHoursPerWeek: 30,
    leaseTerm: "3 yrs remaining, 3-yr renewal at $5,400/mo (below market)",
    growthTrend: "stable",
    sdeMargin: 21,
    multipleOnAsk: 2.77,
    highlights: [
      "Prime downtown Olympia location — high foot traffic & tourist corridor",
      "Below-market lease locked for 3 years — significant cost advantage",
      "Established vendor relationships and curated product mix included",
      "Strong seasonal peaks: 40% of revenue in Q4 holiday season",
    ],
  },
  {
    id: "6",
    name: "Eastside Taqueria Express",
    type: "Restaurant",
    askingPrice: 175000,
    revenue: 480000,
    sde: 82000,
    location: "Renton, WA",
    state: "WA",
    description:
      "Fast-casual Mexican restaurant with loyal lunch and dinner crowd. Streamlined menu of 18 items. Owner-operated with 2 full-time and 3 part-time staff. High-volume delivery through DoorDash/Uber Eats (38% of revenue).",
    yearEstablished: 2018,
    employees: 5,
    ownerHoursPerWeek: 45,
    leaseTerm: "2 yrs remaining, 3-yr renewal at $4,800/mo",
    growthTrend: "stable",
    sdeMargin: 17,
    multipleOnAsk: 2.13,
    highlights: [
      "38% of revenue from delivery platforms — diversified revenue channels",
      "Streamlined 18-item menu reduces complexity and waste",
      "Low asking price at 2.13x SDE — priced for quick sale",
      "Strong repeat customer base with 4.7 ★ on Google (340+ reviews)",
    ],
  },
];
